# Generated by Django 4.0.6 on 2022-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(upload_to='images/')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
